import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";

const TOKENS_PATH = "recursica_tokens.json";
const BRAND_PATH = "recursica_brand.json";
const OUTPUT_PATH = "src/recursica_fonts.css";
const GOOGLE_FONTS_HOST = "fonts.googleapis.com";

/**
 * Every check below throws instead of falling back to a default — a bad or
 * missing font source should break the build/dev-server loudly, not render
 * with a silently wrong (or missing) font.
 */
function fail(message: string): never {
  throw new Error(`[recursica-fonts] ${message}`);
}

function readJson(path: string): unknown {
  if (!existsSync(path)) {
    fail(`${path} not found — required to resolve font imports.`);
  }
  const raw = readFileSync(path, "utf-8");
  try {
    return JSON.parse(raw);
  } catch (err) {
    fail(`${path} is not valid JSON: ${(err as Error).message}`);
  }
}

/**
 * Resolves a `{tokens.font.typefaces.<key>}` reference (as used by
 * `recursica_brand.json`'s `brand.fonts.primary`/`secondary`) to the
 * typeface key it points at.
 */
function typefaceKey(ref: unknown, field: string): string {
  if (typeof ref !== "string") {
    fail(
      `${BRAND_PATH}: brand.fonts.${field}.$value is missing or not a string.`,
    );
  }
  const match = /^\{tokens\.font\.typefaces\.([^}]+)\}$/.exec(ref);
  if (!match) {
    fail(
      `${BRAND_PATH}: brand.fonts.${field}.$value ("${ref}") doesn't reference a tokens.font.typefaces entry.`,
    );
  }
  return match[1];
}

/** Looks up a typeface's Google Fonts URL, validating it as it goes. */
function resolveGoogleFontsUrl(
  typefaces: Record<string, unknown>,
  key: string,
): string {
  if (!Object.hasOwn(typefaces, key)) {
    fail(`"${key}" is not listed in ${TOKENS_PATH} (tokens.font.typefaces).`);
  }
  const typeface = typefaces[key] as Record<string, unknown>;
  const url = (typeface?.$extensions as Record<string, unknown> | undefined)?.[
    "com.google.fonts"
  ] as Record<string, unknown> | undefined;
  const href = url?.url;
  if (typeof href !== "string" || href.length === 0) {
    fail(
      `Typeface "${key}" in ${TOKENS_PATH} has no $extensions."com.google.fonts".url.`,
    );
  }

  let parsed: URL;
  try {
    parsed = new URL(href);
  } catch {
    fail(`Typeface "${key}"'s font URL is not well-formed: "${href}"`);
  }
  if (parsed.protocol !== "https:" || parsed.hostname !== GOOGLE_FONTS_HOST) {
    fail(
      `Typeface "${key}"'s font URL is not a Google Fonts URL (expected https://${GOOGLE_FONTS_HOST}/..., got "${href}").`,
    );
  }

  return href;
}

/**
 * Reads the brand's primary/secondary typefaces out of
 * `recursica_brand.json` + `recursica_tokens.json` and writes their Google
 * Fonts `@import` URLs to `recursica_fonts.css`.
 *
 * This runs at build time (Node, in the Vite process) so the app can import
 * a tiny generated stylesheet instead of `recursica_tokens.json` itself —
 * that file is large and mostly irrelevant to fonts, and importing it
 * directly would pull the whole thing into the client bundle just to read
 * two URLs out of it.
 *
 * Every step is validated with no fallback: a missing file, a typeface not
 * listed in `recursica_tokens.json`, or a malformed/non-Google URL throws
 * and aborts the build rather than emitting something silently wrong.
 */
function generateFontImports(): void {
  const tokens = readJson(TOKENS_PATH) as {
    tokens?: { font?: { typefaces?: Record<string, unknown> } };
  };
  const brand = readJson(BRAND_PATH) as {
    brand?: {
      fonts?: {
        primary?: { $value?: unknown };
        secondary?: { $value?: unknown };
      };
    };
  };

  const typefaces = tokens.tokens?.font?.typefaces;
  if (!typefaces || typeof typefaces !== "object") {
    fail(`${TOKENS_PATH} is missing tokens.font.typefaces.`);
  }

  const fontsBrand = brand.brand?.fonts;
  if (!fontsBrand?.primary || !fontsBrand?.secondary) {
    fail(
      `${BRAND_PATH} is missing brand.fonts.primary and/or brand.fonts.secondary.`,
    );
  }

  const usedKeys = new Set([
    typefaceKey(fontsBrand.primary.$value, "primary"),
    typefaceKey(fontsBrand.secondary.$value, "secondary"),
  ]);

  const urls = new Set<string>();
  for (const key of usedKeys) {
    urls.add(resolveGoogleFontsUrl(typefaces, key));
  }

  const css =
    `/* AUTO-GENERATED by vite.config.ts — do not edit by hand.\n` +
    ` * Regenerated from ${TOKENS_PATH} + ${BRAND_PATH} on every dev/build. */\n` +
    [...urls].map((url) => `@import url("${url}");`).join("\n") +
    "\n";
  writeFileSync(OUTPUT_PATH, css);
}

/** Keeps `recursica_fonts.css` in sync with the brand's typefaces. */
function recursicaFonts(): Plugin {
  return {
    name: "recursica-fonts",
    buildStart() {
      generateFontImports();
      this.addWatchFile(TOKENS_PATH);
      this.addWatchFile(BRAND_PATH);
    },
    configureServer(server) {
      server.watcher.add([TOKENS_PATH, BRAND_PATH]);
      server.watcher.on("change", (file) => {
        if (file.endsWith(TOKENS_PATH) || file.endsWith(BRAND_PATH)) {
          generateFontImports();
        }
      });
    },
  };
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), recursicaFonts()],
});
